// Auto-generated by scripts/sync_phase1_page_assets_to_app.py
// Clean page images only — highlights are drawn at runtime in PageViewer.

export const PHASE1_PAGE_IMAGE_ASSETS: Record<string, number> = {
  im10_page_31: require('@/assets/textbooks/internal-medicine-10/pages/31.webp'),
  im10_page_32: require('@/assets/textbooks/internal-medicine-10/pages/32.webp'),
  im10_page_33: require('@/assets/textbooks/internal-medicine-10/pages/33.webp'),
  im10_page_34: require('@/assets/textbooks/internal-medicine-10/pages/34.webp'),
  im10_page_35: require('@/assets/textbooks/internal-medicine-10/pages/35.webp'),
  im10_page_36: require('@/assets/textbooks/internal-medicine-10/pages/36.webp'),
  im10_page_37: require('@/assets/textbooks/internal-medicine-10/pages/37.webp'),
  im10_page_38: require('@/assets/textbooks/internal-medicine-10/pages/38.webp'),
  im10_page_39: require('@/assets/textbooks/internal-medicine-10/pages/39.webp'),
}

export const PHASE1_ASTHMA_PAGE_LABELS = [
"31", "32", "33", "34", "35", "36", "37", "38", "39"
] as const
