// Auto-generated by scripts/sync_phase1_page_assets_to_app.py
// Clean page images only — highlights are drawn at runtime in PageViewer.

export const PHASE1_PAGE_IMAGE_ASSETS: Record<string, number> = {
  im10_page_62: require('@/assets/textbooks/internal-medicine-10/pages/62.webp'),
  im10_page_63: require('@/assets/textbooks/internal-medicine-10/pages/63.webp'),
  im10_page_64: require('@/assets/textbooks/internal-medicine-10/pages/64.webp'),
  im10_page_65: require('@/assets/textbooks/internal-medicine-10/pages/65.webp'),
  im10_page_66: require('@/assets/textbooks/internal-medicine-10/pages/66.webp'),
  im10_page_67: require('@/assets/textbooks/internal-medicine-10/pages/67.webp'),
  im10_page_68: require('@/assets/textbooks/internal-medicine-10/pages/68.webp'),
  im10_page_69: require('@/assets/textbooks/internal-medicine-10/pages/69.webp'),
  im10_page_70: require('@/assets/textbooks/internal-medicine-10/pages/70.webp'),
}

export const PHASE1_ASTHMA_PAGE_LABELS = [
"62", "63", "64", "65", "66", "67", "68", "69", "70"
] as const
