import type { CaseQualityRecord } from './case-quality.ts'

export type AlphaCaseSeed = CaseQualityRecord & { specialty: string }

const REVIEWER = 'alpha-demo-medical-reviewer'
const REVIEWED_AT = '2026-06-13T00:00:00.000Z'

const SCORING_RUBRIC = {
  diagnosis: {
    weight: 40,
    exactMatch: 40,
    partialMatch: 30,
    categoryMatch: 15,
    hitDifferential: 8,
    wrong: 0,
  },
  differential: {
    weight: 20,
    threeOrMoreWithReasoning: 20,
    threeOrMore: 16,
    two: 12,
    one: 8,
    none: 0,
    missingCritical: -3,
  },
  evidence: {
    weight: 20,
    coverageWeight: 0.5,
    associationWeight: 0.3,
    interpretationWeight: 0.2,
  },
  treatment: {
    weight: 20,
    criticalCoverageWeight: 0.4,
    safetyWeight: 0.3,
    reasonablenessWeight: 0.3,
  },
} as const

function buildCase(spec: {
  id: string
  title: string
  chiefComplaint: string
  specialty: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  age: number
  presentationContext: string
  patientComplaint: string
  diagnosis: string
  diagnosisAliases: string[]
  icd10: string
  differentialA: string
  differentialB: string
  historyEvidence: string
  examEvidence: string
  testEvidence: string
  immediateTreatment: string
  definitiveTreatment: string
  dangerousTreatment: string
}): AlphaCaseSeed {
  return {
    id: spec.id,
    specialty: spec.specialty,
    case_code: spec.id,
    title: spec.title,
    chief_complaint: spec.chiefComplaint,
    difficulty: spec.difficulty,
    demographics: {
      age: spec.age,
      presentationContext: spec.presentationContext,
    },
    patient_world: {
      chiefComplaint: spec.patientComplaint,
      history: {
        presentIllness: [
          {
            id: 'onset',
            field: '起病',
            answer: '突然起病',
            patientVoice: '突然就开始不舒服了',
          },
          {
            id: 'site',
            field: '部位',
            answer: '与主诉相关部位',
            patientVoice: '就是现在说的这个地方',
          },
          {
            id: 'duration',
            field: '时长',
            answer: '数小时',
            patientVoice: '已经好几个小时了',
          },
        ],
      },
      physicalExam: {
        general: { findings: [spec.examEvidence] },
      },
      investigations: {
        primary: { result: spec.testEvidence },
      },
    },
    ground_truth: {
      diagnosis: {
        primary: spec.diagnosis,
        primaryAliases: spec.diagnosisAliases,
        icd10: spec.icd10,
      },
      differentials: [
        {
          diagnosis: spec.differentialA,
          aliases: [],
          keyDiscriminator: `${spec.differentialA}特征`,
          mustExclude: true,
          supportAgainst: '不支持该诊断',
        },
        {
          diagnosis: spec.differentialB,
          aliases: [],
          keyDiscriminator: `${spec.differentialB}特征`,
          mustExclude: false,
          supportAgainst: '需鉴别',
        },
      ],
      criticalEvidence: {
        forDiagnosis: {
          fromHistory: [spec.historyEvidence],
          fromExam: [spec.examEvidence],
          fromTests: [spec.testEvidence],
        },
      },
      treatment: {
        immediate: [{ action: spec.immediateTreatment, isCritical: true, aliases: [] }],
        definitive: [{ action: spec.definitiveTreatment, isCritical: true, aliases: [] }],
        dangerous: [{ action: spec.dangerousTreatment, penalty: 10, aliases: [] }],
      },
    },
    scoring_rubric: SCORING_RUBRIC,
    is_active: true,
    review_status: 'approved',
    reviewed_by: REVIEWER,
    reviewed_at: REVIEWED_AT,
  }
}

export const ALPHA_CASE_LIBRARY: AlphaCaseSeed[] = [
  buildCase({
    id: 'CC_CP_001',
    title: '急性胸痛 — STEMI',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'beginner',
    age: 65,
    presentationContext: '因胸痛3小时来急诊',
    patientComplaint: '胸口疼了3个小时',
    diagnosis: '急性ST段抬高型心肌梗死',
    diagnosisAliases: ['STEMI', '急性心肌梗死'],
    icd10: 'I21.3',
    differentialA: '主动脉夹层',
    differentialB: '急性心包炎',
    historyEvidence: '持续胸痛伴大汗',
    examEvidence: '血压偏低，心率偏快',
    testEvidence: '心电图ST段抬高',
    immediateTreatment: '双联抗血小板+抗凝',
    definitiveTreatment: '急诊PCI再灌注',
    dangerousTreatment: '未稳定血流动力学即使用β阻滞剂',
  }),
  buildCase({
    id: 'CC_CP_002',
    title: '急性胸痛 — 不稳定型心绞痛',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'beginner',
    age: 58,
    presentationContext: '反复胸痛1天来诊',
    patientComplaint: '胸口闷痛反复发作',
    diagnosis: '不稳定型心绞痛',
    diagnosisAliases: ['UA', '不稳定心绞痛'],
    icd10: 'I20.0',
    differentialA: '急性心肌梗死',
    differentialB: '胃食管反流病',
    historyEvidence: '静息痛，活动加重',
    examEvidence: '心音正常，无杂音',
    testEvidence: '肌钙蛋白阴性，心电图ST-T改变',
    immediateTreatment: '阿司匹林+硝酸甘油',
    definitiveTreatment: '抗缺血治疗并评估血运重建',
    dangerousTreatment: '未排除心梗即出院',
  }),
  buildCase({
    id: 'CC_CP_003',
    title: '急性胸痛 — 肺栓塞',
    chiefComplaint: 'chest_pain',
    specialty: 'respiratory',
    difficulty: 'intermediate',
    age: 42,
    presentationContext: '术后突发胸痛、呼吸困难',
    patientComplaint: '突然胸痛还喘不上气',
    diagnosis: '急性肺栓塞',
    diagnosisAliases: ['肺栓塞', 'PE'],
    icd10: 'I26.9',
    differentialA: '急性心肌梗死',
    differentialB: '气胸',
    historyEvidence: '术后卧床，突发呼吸困难',
    examEvidence: '呼吸急促，血氧下降',
    testEvidence: 'D-二聚体升高，CTPA阳性',
    immediateTreatment: '吸氧并抗凝',
    definitiveTreatment: '根据风险分层选择抗凝或溶栓',
    dangerousTreatment: '高风险PE未抗凝',
  }),
  buildCase({
    id: 'CC_CP_004',
    title: '急性胸痛 — 主动脉夹层',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'advanced',
    age: 55,
    presentationContext: '撕裂样胸痛急诊就诊',
    patientComplaint: '胸口像被撕开一样疼',
    diagnosis: '主动脉夹层',
    diagnosisAliases: ['夹层', 'AD'],
    icd10: 'I71.0',
    differentialA: '急性心肌梗死',
    differentialB: '急性心包炎',
    historyEvidence: '突发撕裂样胸背痛',
    examEvidence: '双上肢血压不对称',
    testEvidence: 'CTA显示夹层征象',
    immediateTreatment: '严格控制血压和心率',
    definitiveTreatment: '根据分型选择手术或药物',
    dangerousTreatment: '夹层误用溶栓',
  }),
  buildCase({
    id: 'CC_CP_005',
    title: '急性胸痛 — 气胸',
    chiefComplaint: 'chest_pain',
    specialty: 'respiratory',
    difficulty: 'beginner',
    age: 24,
    presentationContext: '瘦高男性突发胸痛',
    patientComplaint: '一侧胸口突然刺痛',
    diagnosis: '自发性气胸',
    diagnosisAliases: ['气胸'],
    icd10: 'J93.9',
    differentialA: '急性心肌梗死',
    differentialB: '肺栓塞',
    historyEvidence: '突发单侧胸痛',
    examEvidence: '患侧呼吸音减弱',
    testEvidence: '胸片见肺压缩线',
    immediateTreatment: '吸氧并观察生命体征',
    definitiveTreatment: '胸腔闭式引流',
    dangerousTreatment: '张力性气胸未减压',
  }),
  buildCase({
    id: 'CC_CP_006',
    title: '急性胸痛 — 急性心包炎',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'intermediate',
    age: 36,
    presentationContext: '发热后胸痛来诊',
    patientComplaint: '胸口疼，深呼吸更明显',
    diagnosis: '急性心包炎',
    diagnosisAliases: ['心包炎'],
    icd10: 'I30.9',
    differentialA: '急性心肌梗死',
    differentialB: '胸膜炎',
    historyEvidence: '近期病毒感染史',
    examEvidence: '心包摩擦音',
    testEvidence: '心电图广泛导联ST抬高',
    immediateTreatment: '非甾体抗炎药',
    definitiveTreatment: '针对病因治疗并随访',
    dangerousTreatment: '心包炎误溶栓',
  }),
  buildCase({
    id: 'CC_CP_007',
    title: '急性胸痛 — 反流性食管炎',
    chiefComplaint: 'chest_pain',
    specialty: 'gastroenterology',
    difficulty: 'beginner',
    age: 48,
    presentationContext: '餐后烧心样胸痛',
    patientComplaint: '吃完饭胸口烧灼痛',
    diagnosis: '反流性食管炎',
    diagnosisAliases: ['胃食管反流', 'GERD'],
    icd10: 'K21.0',
    differentialA: '急性心肌梗死',
    differentialB: '不稳定型心绞痛',
    historyEvidence: '餐后烧灼痛，平卧加重',
    examEvidence: '心肺查体无明显异常',
    testEvidence: '心电图和肌钙蛋白正常',
    immediateTreatment: '质子泵抑制剂',
    definitiveTreatment: '生活方式干预并评估反流',
    dangerousTreatment: '未排除ACS即按GERD处理',
  }),
  buildCase({
    id: 'CC_CP_008',
    title: '急性胸痛 — 急性心肌炎',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'intermediate',
    age: 29,
    presentationContext: '感冒后胸闷胸痛',
    patientComplaint: '感冒后胸口闷痛',
    diagnosis: '急性心肌炎',
    diagnosisAliases: ['心肌炎'],
    icd10: 'I40.9',
    differentialA: '急性心肌梗死',
    differentialB: '心包炎',
    historyEvidence: '前驱病毒感染',
    examEvidence: '心率增快，心音低钝',
    testEvidence: '肌钙蛋白轻度升高，MRI心肌水肿',
    immediateTreatment: '休息并监护心律',
    definitiveTreatment: '支持治疗并评估心衰',
    dangerousTreatment: '心肌炎剧烈运动',
  }),
  buildCase({
    id: 'CC_CP_009',
    title: '急性胸痛 — 肋软骨炎',
    chiefComplaint: 'chest_pain',
    specialty: 'general',
    difficulty: 'beginner',
    age: 33,
    presentationContext: '局部压痛样胸痛',
    patientComplaint: '胸口某个点一按就疼',
    diagnosis: '肋软骨炎',
    diagnosisAliases: ['肋软骨炎', 'Tietze综合征'],
    icd10: 'M94.0',
    differentialA: '急性心肌梗死',
    differentialB: '肺栓塞',
    historyEvidence: '局部压痛，与呼吸关系不大',
    examEvidence: '肋软骨压痛阳性',
    testEvidence: '心电图和肌钙蛋白正常',
    immediateTreatment: '止痛对症处理',
    definitiveTreatment: '观察并排除危重胸痛',
    dangerousTreatment: '未排除ACS即仅止痛',
  }),
  buildCase({
    id: 'CC_CP_010',
    title: '急性胸痛 — 急性胰腺炎相关胸痛',
    chiefComplaint: 'chest_pain',
    specialty: 'gastroenterology',
    difficulty: 'intermediate',
    age: 52,
    presentationContext: '上腹痛放射至胸部',
    patientComplaint: '上腹剧痛还扯到胸口',
    diagnosis: '急性胰腺炎',
    diagnosisAliases: ['胰腺炎'],
    icd10: 'K85.9',
    differentialA: '急性心肌梗死',
    differentialB: '主动脉夹层',
    historyEvidence: '饮酒或高脂餐后上腹痛',
    examEvidence: '上腹压痛明显',
    testEvidence: '血淀粉酶和脂肪酶升高',
    immediateTreatment: '禁食、补液、镇痛',
    definitiveTreatment: '病因治疗并监护并发症',
    dangerousTreatment: '胰腺炎误溶栓',
  }),
  buildCase({
    id: 'CC_CP_011',
    title: '急性胸痛 — 肺炎胸膜炎',
    chiefComplaint: 'chest_pain',
    specialty: 'respiratory',
    difficulty: 'beginner',
    age: 61,
    presentationContext: '咳嗽发热伴胸痛',
    patientComplaint: '咳嗽时胸口更疼',
    diagnosis: '肺炎伴胸膜炎',
    diagnosisAliases: ['肺炎', '胸膜炎'],
    icd10: 'J18.9',
    differentialA: '急性心肌梗死',
    differentialB: '肺栓塞',
    historyEvidence: '咳嗽发热数天',
    examEvidence: '语颤增强，呼吸音粗',
    testEvidence: '胸片浸润影，白细胞升高',
    immediateTreatment: '抗感染治疗',
    definitiveTreatment: '根据病原学调整抗生素',
    dangerousTreatment: '重症肺炎未及时抗感染',
  }),
  buildCase({
    id: 'CC_CP_012',
    title: '急性胸痛 — 焦虑相关胸痛',
    chiefComplaint: 'chest_pain',
    specialty: 'psychiatry',
    difficulty: 'beginner',
    age: 27,
    presentationContext: '紧张后胸闷胸痛',
    patientComplaint: '一紧张就胸口发紧',
    diagnosis: '焦虑相关胸痛',
    diagnosisAliases: ['焦虑障碍', '惊恐发作'],
    icd10: 'F41.9',
    differentialA: '急性心肌梗死',
    differentialB: '不稳定型心绞痛',
    historyEvidence: '情绪诱发，持续时间短',
    examEvidence: '查体无客观异常',
    testEvidence: '心电图和肌钙蛋白正常',
    immediateTreatment: '先排除ACS后安抚',
    definitiveTreatment: '心理干预与随访',
    dangerousTreatment: '未排除ACS即诊断为焦虑',
  }),
  buildCase({
    id: 'CC_CP_013',
    title: '急性胸痛 — 急性胆囊炎',
    chiefComplaint: 'chest_pain',
    specialty: 'general_surgery',
    difficulty: 'intermediate',
    age: 49,
    presentationContext: '右上腹痛伴胸闷',
    patientComplaint: '右上腹疼还闷到胸口',
    diagnosis: '急性胆囊炎',
    diagnosisAliases: ['胆囊炎'],
    icd10: 'K81.0',
    differentialA: '急性心肌梗死',
    differentialB: '下壁心肌梗死',
    historyEvidence: '高脂餐后右上腹痛',
    examEvidence: 'Murphy征阳性',
    testEvidence: '超声示胆囊结石并壁增厚',
    immediateTreatment: '禁食、补液、抗感染',
    definitiveTreatment: '评估手术时机',
    dangerousTreatment: '胆囊炎延误抗感染',
  }),
  buildCase({
    id: 'CC_CP_014',
    title: '急性胸痛 — 急性心力衰竭',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'intermediate',
    age: 70,
    presentationContext: '夜间憋醒伴胸痛',
    patientComplaint: '晚上喘不上气胸口也闷痛',
    diagnosis: '急性心力衰竭',
    diagnosisAliases: ['急性心衰', 'AHF'],
    icd10: 'I50.9',
    differentialA: '急性心肌梗死',
    differentialB: '肺栓塞',
    historyEvidence: '端坐呼吸，夜间憋醒',
    examEvidence: '双肺湿啰音，颈静脉怒张',
    testEvidence: 'BNP升高，胸片肺淤血',
    immediateTreatment: '利尿、扩血管、氧疗',
    definitiveTreatment: '明确诱因并优化心衰治疗',
    dangerousTreatment: '急性心衰误用β阻滞剂负荷剂量',
  }),
  buildCase({
    id: 'CC_CP_015',
    title: '急性胸痛 — 变异型心绞痛',
    chiefComplaint: 'chest_pain',
    specialty: 'cardiology',
    difficulty: 'advanced',
    age: 46,
    presentationContext: '夜间静息胸痛发作',
    patientComplaint: '半夜胸口突然绞痛',
    diagnosis: '变异型心绞痛',
    diagnosisAliases: ['血管痉挛性心绞痛'],
    icd10: 'I20.1',
    differentialA: '急性心肌梗死',
    differentialB: '胃食管反流病',
    historyEvidence: '静息夜间发作，活动不一定诱发',
    examEvidence: '发作间期查体可正常',
    testEvidence: '发作时心电图ST段抬高',
    immediateTreatment: '硝酸甘油舌下含服',
    definitiveTreatment: '钙通道阻滞剂并避免诱因',
    dangerousTreatment: '痉挛性心绞痛误用大剂量β阻滞剂',
  }),
]