#!/usr/bin/env python3
"""Generate docs/CURRENT_STATE.md from validated YAML state."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from validate_project_state import ProjectStateError, validate_repository


def _escape_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _object_table(objects: list[dict[str, Any]], reason_label: str) -> list[str]:
    lines = [
        f"| ID | Title | Status | {reason_label} |",
        "|---|---|---|---|",
    ]
    for obj in sorted(objects, key=lambda item: item["id"]):
        reason = obj.get("blocked_reason") or obj.get("completed_at") or ""
        lines.append(
            "| "
            + " | ".join(
                _escape_cell(value)
                for value in (
                    obj["id"],
                    obj["title"],
                    obj["status"],
                    reason,
                )
            )
            + " |"
        )
    return lines


def _relevant_adrs(
    active: dict[str, Any] | None,
    adrs: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    if not active:
        return []
    terms = {
        active["id"],
        *active.get("scope", []),
        *active.get("adr_tags", []),
    }
    relevant = []
    for adr in adrs:
        if adr["status"] != "accepted":
            continue
        if terms.intersection(adr.get("applies_to", [])):
            relevant.append(adr)
    return sorted(relevant, key=lambda item: item["id"])


def render_current_state(validated: dict[str, Any]) -> str:
    state = validated["state"]
    project = state["project"]
    active = state["active"]
    blocked = [obj for obj in state["blocked"] if obj["status"] == "blocked"]
    paused = [obj for obj in state["blocked"] if obj["status"] == "paused"]
    completed = [
        obj for obj in state["completed"] if obj["status"] == "completed"
    ]
    archived = [
        obj for obj in state["completed"] if obj["status"] == "archived"
    ]
    relevant_adrs = _relevant_adrs(active, validated["adr_index"]["adrs"])

    lines = [
        "# Current State",
        "",
        "> AUTO-GENERATED by `python scripts/generate_current_state.py`.",
        "> Do not edit this file manually. Edit `state/*.yaml`, validate, then regenerate.",
        "",
        "## Project",
        "",
        f"- Name: `{project['name']}`",
        f"- Phase: `{project['phase']}`",
        "",
        "## Active Object",
        "",
    ]

    if active:
        lines.extend(
            [
                f"### `{active['id']}`: {active['title']}",
                "",
                active["objective"],
                "",
                "**Scope**",
                "",
                *[f"- `{item}`" for item in active["scope"]],
                "",
                "**Acceptance Criteria**",
                "",
                *[f"- {item}" for item in active["acceptance_criteria"]],
                "",
            ]
        )
    else:
        lines.extend(
            [
                "None. The project is in a recoverable stable state.",
                "",
            ]
        )

    lines.extend(["## Blocked", ""])
    lines.extend(
        _object_table(blocked, "Blocked Reason")
        if blocked
        else ["No blocked objects."]
    )
    lines.extend(["", "## Paused", ""])
    lines.extend(
        _object_table(paused, "Pause Reason")
        if paused
        else ["No paused objects."]
    )
    lines.extend(["", "## Completed", ""])
    lines.extend(
        _object_table(completed, "Completed At")
        if completed
        else ["No completed objects."]
    )
    lines.extend(["", "## Archived", ""])
    lines.extend(
        _object_table(archived, "Archived At")
        if archived
        else ["No archived objects."]
    )
    lines.extend(["", "## Applicable Accepted ADRs", ""])

    if relevant_adrs:
        lines.extend(
            [
                f"- [{adr['id']}: {adr['title']}](../{adr['path']})"
                for adr in relevant_adrs
            ]
        )
    elif active:
        lines.append("No accepted ADR is indexed for the current Active Object.")
    else:
        lines.append("No Active Object; ADR loading is deferred until activation.")

    lines.extend(
        [
            "",
            "## State Sources",
            "",
            "- `state/active_object.yaml`",
            "- `state/blocked_objects.yaml`",
            "- `state/completed_objects.yaml`",
            "- `docs/ADR_INDEX.yaml`",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root (defaults to the parent of scripts/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output path (defaults to docs/CURRENT_STATE.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated content differs from the existing file",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    output = args.output or root / "docs" / "CURRENT_STATE.md"
    if not output.is_absolute():
        output = root / output

    try:
        validated = validate_repository(root)
        content = render_current_state(validated)
    except ProjectStateError as exc:
        print(
            f"CURRENT_STATE.md was not generated because validation failed: {exc}",
            file=sys.stderr,
        )
        return 1

    if args.check:
        if not output.is_file():
            print(f"Generated state is missing: {output}", file=sys.stderr)
            return 1
        existing = output.read_text(encoding="utf-8").replace("\r\n", "\n")
        if existing != content:
            print(
                "docs/CURRENT_STATE.md is stale. Run: "
                "python scripts/generate_current_state.py",
                file=sys.stderr,
            )
            return 1
        print("docs/CURRENT_STATE.md is current.")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
