#!/usr/bin/env python3
"""Copy Phase 1 webp pages into Expo assets and emit require() registry."""
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "generated/textbooks/internal-medicine-10/pages"
DST = ROOT / "assets/textbooks/internal-medicine-10/pages"
OUT = ROOT / "constants/phase1PageImageAssets.ts"
# Printed page labels (31-39) for the asthma pilot. Phase 6A confirmed:
# pageLabel is the printed label, NOT the PDF page number (62-70).
LABELS = [str(p) for p in range(31, 40)]


def main() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    keys: list[tuple[str, str]] = []
    for label in LABELS:
        src = SRC / f"{label}.webp"
        if not src.exists():
            raise SystemExit(f"Missing {src}")
        shutil.copy2(src, DST / f"{label}.webp")
        keys.append((f"im10_page_{label}", label))

    lines = [
        "// Auto-generated by scripts/sync_phase1_page_assets_to_app.py",
        "// Clean page images only — highlights are drawn at runtime in PageViewer.",
        "",
        "export const PHASE1_PAGE_IMAGE_ASSETS: Record<string, number> = {",
    ]
    for key, label in keys:
        lines.append(
            f"  {key}: require('@/assets/textbooks/internal-medicine-10/pages/{label}.webp'),"
        )
    lines.append("}")
    lines.append("")
    lines.append("export const PHASE1_ASTHMA_PAGE_LABELS = [")
    lines.append(", ".join(f'"{label}"' for label in LABELS))
    lines.append("] as const")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[sync] copied {len(keys)} pages -> {DST}")
    print(f"[sync] wrote {OUT}")


if __name__ == "__main__":
    main()